### ISSUE TITLE
If you want to OSD for use_lib_cvbs_bitluni to work use this code osd.cpp

### ISSUE THREAD

**Issue by sandro-teh** [rpsubc8/ESP32TinyMCUMEesp81#1]
void SDLClear()
{
 //for (int y=0; y<(auxSurface->w); y++)
 // for (int x=0; x<(auxSurface->h); x++)
 //  SDLputpixel(auxSurface,x,y,1);
 //for (int y=0; y<200; y++)
 // for (int x=0; x<320; x++)
#ifdef use_lib_cvbs_bitluni
  for (int y=0; y<200; y++){
   for (int x=0; x<80; x++)
   {   
    //gb_buffer_cvbs32[y][x]= a32;
    gb_buffer_cvbs32[y][x]= 0;
   }
  }

#else

 for (int y=0; y<200; y++)
 {
  #ifdef use_lib_vga360x200
   for (int x=0; x<360; x++)
  #else
   for (int x=0; x<320; x++)
  #endif
   {
    jj_fast_putpixel(x,y,0);
   }   
 }
 //SDLputpixel(auxSurface,x,y,3);  
#endif

  
}

**Comment by rpsubc8** [comment]
Thank you very much. 
I have added your correction. If I am not mistaken, it should work in principle.
